__version__ = "0.0.1"
__author__ = "Kadir Nar"
__license__ = "Apache License 2.0"
__url__ = "https://github.com/kadirnar/DatasetPlus"
__summary__ = "DatasetPlus: Enhanced dataset management utilities for Hugging Face Hub."
__library_name__ = "datasetplus"
